[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "autonomous-fed"
version = "0.0.1"
description = "A package for simulating and analyzing the effects of monetary policy in a federal reserve context."
authors = [
    "Nikhil Sunder <nss106@miami.edu>",
    "Eritokritos Skordilis <eskordilis@bus.miami.edu>"
]
readme = "README.md"
repository = "https://erskordi.github.io/Autonomous_Fed/"
packages = [{include = "autonomous_fed", from = "src"}]
include = ["src/autonomous_fed/py.typed"]
classifiers = [
    "Programming Language :: Python :: 3",
]
keywords = []

[tool.poetry.dependencies]
python = ">=3.10, <4.0"
matplotlib = "*"
pandas = "*"
statsmodels = "*"
fedfred = "*"
numpy = "*"
python-dateutil = "*"
torch = "*"


[tool.poetry.group.dev.dependencies]
pandas-stubs = "*"
pytest = "*"
pytest-cov = "*"
pylint = "*"
mypy = "*"
bandit = "*"
pip-audit = "*"
pre-commit = "*"
hypothesis = "*"
pytest-mock = "*"
ipympl = "*"
ipywidgets = "*"
jupyterlab-lsp = "*"
nbdime = "*"
types-python-dateutil = "*"

[tool.mypy]
files = "src/autonomous_fed"
ignore_missing_imports = true

[tool.pylint]
max-line-length = 250
disable = ["E0401", "R0902", "R0913", "R0917", "R0903", "R1705", "R0911", "R0912", "R0914", "R0915", "R1735", "W0222"]
ignore-patterns = [".*\\.pyi$"]

[tool.bandit]
exclude_dirs = ["tests"]

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing --cov-report=html"
testpaths = ["tests"]
pythonpath = "src"

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
]
