__title__ = "linear_environment"
__description__ = "A package for solving linear economic environments using SVAR models."
__version__ = "0.0.1"
__author__ = "Nikhil Sunder"
__url__ = "https://github.com/erskordi/Autonnomous_Fed"